name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  build_executable:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'  #17 wär vielleicht besser
          cache: 'maven' #Caching, schon Schulinternet
      - name: Build with Maven
        run: |  #durch | können mehrer Befehle angegeben werden
          mvn -B -DskipTests package
          ls -lh target
          cp src/main/docker/Dockerfile ./target
          docker build --tag ghcr.io/${{ github.repository }}/backend:latest ./target
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
